/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001b3d",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-container": "#006f1c",
        "surface-container-high": "#e7e8e9",
        "primary": "#00478d",
        "outline": "#727783",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-primary-container": "#c8daff",
        "primary-container": "#005eb8",
        "surface-variant": "#e1e3e4",
        "surface-tint": "#005db6",
        "on-primary": "#ffffff",
        "on-surface-variant": "#424752",
        "on-secondary-fixed-variant": "#005047",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3132",
        "on-error-container": "#93000a",
        "on-secondary-container": "#006f62",
        "on-secondary-fixed": "#00201b",
        "tertiary": "#005413",
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary-fixed-variant": "#005313",
        "secondary-container": "#94f0df",
        "surface-container-highest": "#e1e3e4",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#98f994",
        "outline-variant": "#c2c6d4",
        "secondary-fixed-dim": "#7ad7c6",
        "inverse-primary": "#a9c7ff",
        "on-background": "#191c1d",
        "tertiary-fixed-dim": "#7ddc7a",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed": "#97f3e2",
        "on-tertiary-fixed": "#002204",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#90f08c",
        "on-primary-fixed-variant": "#00468c",
        "surface": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "secondary": "#006b5e",
        "background": "#f8f9fa"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
